theme: jekyll-theme-cayman
title: Learning Convolutional Transforms for Point Cloud Geometry Compression
description: Maurice Quach and Giuseppe Valenzise and Frederic Dufaux
google_analytics: UA-139540122-1